// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPIService.LeaderboardService;

#nullable disable

namespace WebAPIService.Migrations
{
    [DbContext(typeof(LeaderboardDbContext))]
    [Migration("20250818082041_WipeoutShooter")]
    partial class WipeoutShooter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("WebAPIService.GameServices.CODEGLUE.Entities.WipeoutShooterScoreboardEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExtraData1")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraData2")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraData3")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraData4")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraData5")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PsnId")
                        .HasColumnType("TEXT");

                    b.Property<float>("Score")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WipeoutShooterScoreboardEntry", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
