// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPIService.LeaderboardService;

#nullable disable

namespace WebAPIService.Migrations
{
    [DbContext(typeof(LeaderboardDbContext))]
    [Migration("20250818124501_WebAPIBatch1")]
    partial class WebAPIBatch1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("WebAPIService.GameServices.CODEGLUE.Entities.WipeoutShooterScoreboardEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExtraData1")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraData2")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraData3")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraData4")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraData5")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PsnId")
                        .HasColumnType("TEXT");

                    b.Property<float>("Score")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WipeoutShooterScoreboardEntry", (string)null);
                });

            modelBuilder.Entity("WebAPIService.GameServices.COGS.Entities.CogsScoreboardEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExtraData1")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraData2")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraData3")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraData4")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraData5")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PsnId")
                        .HasColumnType("TEXT");

                    b.Property<float>("Score")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CogsScoreboardEntry", (string)null);
                });

            modelBuilder.Entity("WebAPIService.GameServices.HEAVYWATER.Entities.HexxScoreboardEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExtraData1")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraData2")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraData3")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraData4")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraData5")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PsnId")
                        .HasColumnType("TEXT");

                    b.Property<float>("Score")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HexxScoreboardEntry", (string)null);
                });

            modelBuilder.Entity("WebAPIService.GameServices.HOMELEADERBOARDS.Entities.HomeScoreboardEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExtraData1")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraData2")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraData3")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraData4")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraData5")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PsnId")
                        .HasColumnType("TEXT");

                    b.Property<float>("Score")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HomeScoreboardEntry", (string)null);
                });

            modelBuilder.Entity("WebAPIService.GameServices.JUGGERNAUT.clearasil.Entities.ClearasilScoreBoardEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExtraData1")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraData2")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraData3")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraData4")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraData5")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PsnId")
                        .HasColumnType("TEXT");

                    b.Property<float>("Score")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ClearasilScoreBoardEntry", (string)null);
                });

            modelBuilder.Entity("WebAPIService.GameServices.NDREAMS.Aurora.Entities.OrbrunnerScoreBoardEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExtraData1")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraData2")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraData3")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraData4")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraData5")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PsnId")
                        .HasColumnType("TEXT");

                    b.Property<float>("Score")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OrbrunnerScoreBoardEntry", (string)null);
                });

            modelBuilder.Entity("WebAPIService.GameServices.OHS.Entities.OHSScoreboardEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExtraData1")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraData2")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraData3")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraData4")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraData5")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PsnId")
                        .HasColumnType("TEXT");

                    b.Property<float>("Score")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OHSScoreboardEntry", (string)null);
                });

            modelBuilder.Entity("WebAPIService.GameServices.RCHOME.Entities.FiringRangeScoreBoardEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExtraData1")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraData2")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraData3")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraData4")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraData5")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PsnId")
                        .HasColumnType("TEXT");

                    b.Property<float>("Score")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FiringRangeScoreBoardEntry", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
