using System.Linq;
using System.Xml.Linq;

namespace WebAPIService.GameServices.PSHOME.HELLFIRE.Entities.HomeTycoon
{
    internal class TycoonFileList
    {
        public static string[] BuildingsFilenames = XDocument.Parse(@"<BuildingList>
                                      <Building>
                                        <Filename>Grass.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>UTL_NE_TownHall_A.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>Road1.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>Road.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>RoadT.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>RoadCurve.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>RoadEnd.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>RoadCross.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>UTL_NE_RampFull_mid.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>UTL_NE_RampFull_end.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>UTL_NE_RampFull_side.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>RES_NE_NeighborhoodHouses_A.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>UTL_TU_Watertower_A.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>UTL_TU_Windmill_A.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>COM_GD_SmBusinessBlk_A.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>RES_NE_SmApartment_A.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>COM_NE_Farm_A.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>Park1.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>COM_GD_RegionalHQ_A.xml</Filename>
                                      </Building>
                                      <!-- Added at completion of S1 -->
                                      <Building>
                                        <Filename>COM_GD_HighRiseBusiness_B.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>COM_NE_BusinessTower_A.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>COM_NE_HighRiseBusiness_A.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>COM_NE_HighRiseBusiness_B.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>COM_NE_Mall.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>COM_NE_Factory.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>RES_NE_Estate_A.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>RES_NE_Estate_B.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>RES_NE_HighRiseCondo_A.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>RES_NE_HighRiseCondo_B.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>RES_NE_SmApartment_B.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>RES_NE_LgApartment_B.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>UTL_NE_ElectricTower.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>UTL_NE_Highway_A.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>UTL_NE_Lake_A.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>UTL_NE_Lake_B.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>UTL_NE_NovusRecruitStation.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>UTL_NE_Road_Straight_TreeCover.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>Park2.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>RES_GD_LgApartment_A.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>RES_NE_HighRiseCondo_C.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>RES_NE_LgApartment_C.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>RES_NE_NeighborhoodHouses_C.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>RES_NE_SmApartment_C.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>UTL_NE_FireDepartment.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>COM_NE_Dealership.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>UTL_NE_PoliceStation.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>COM_NE_OilWell.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>UTL_GD_VehicleShowroom.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>COM_GD_Oil_Well.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>UTL_NE_Ramp.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>UTL_NE_Loop.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>COM_NE_Warehouse.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>COM_TU_BusinessTower_C.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>COM_TU_BusinessTower_B.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>UTL_NE_Hospital.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>COM_NE_BusinessTower_C.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>COM_GD_BusinessTower_C.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>RES_TU_HighRiseCondo_C.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>RES_GD_HighRiseCondo_C.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>RES_GD_HighRiseCondo_D.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>RES_TU_HighRiseCondo_D.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>RES_NE_NeighborhoodHouses_B.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>RES_GD_Estate_B.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>UTL_GD_CoalPowerPlant.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>UTL_TU_WindmillArray.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>COM_NE_FarmMkt_A.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>UTL_TU_SolarPwrArray.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>COM_NE_Zoo.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>COM_NE_Stadium_A.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>COM_NE_Stadium_B.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>COM_NE_Stadium_C.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>COM_NE_Donut.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>COM_TU_HighRiseBusiness_A.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>COM_GD_HighRiseBusiness_A.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>COM_TU_HighRiseBusiness_B.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>COM_GD_HighRiseBusiness_C.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>COM_GD_HighRiseBusiness_D.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>COM_GD_Factory.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>RES_TU_SmApartment_C.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>RES_TU_LgApartment_C.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>RES_TU_LgApartment_D.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>RES_TU_NeighborhoodHouses_C.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>UTL_GD_NuclearPwrPlant.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>COM_TU_Area52.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>COM_TU_SmBusinessBlk_B.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>UTL_NE_Road_StartLine.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>UTL_NE_Road_FinishLine.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>COM_GD_HighRiseBusiness_A_Gold.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>COM_NE_BusinessTower_A_Gold.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>RES_GD_Estate_B_Gold.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>RES_NE_Estate_B_Gold.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>RES_NE_NeighborhoodHouses_A_OceanBreeze.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>RES_NE_NeighborhoodHouses_B_OceanBreeze.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>RES_NE_LgApartment_B_OceanBreeze.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>RES_NE_Estate_B_OceanBreeze.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>RES_NE_NeighborhoodHouses_A_Halloween.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>RES_NE_NeighborhoodHouses_B_Halloween.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>RES_NE_Estate_B_Halloween.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>RES_NE_NeighborhoodHouses_A_Winter.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>RES_NE_NeighborhoodHouses_B_Winter.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>RES_NE_Estate_B_Winter.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>Park1_Winter.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>COM_NE_AmusementPark.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>UTL_NE_PoliceStation_Metro.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>COM_NE_Diner.xml</Filename>
                                      </Building>
                                      <Building>
                                        <Filename>COM_NE_Pharmacy.xml</Filename>
                                      </Building>
                                    </BuildingList>").Descendants("Building")
                                    .Select(b => b.Element("Filename")?.Value)
                                    .Where(f => !string.IsNullOrEmpty(f))
                                    .ToArray();

        public static string[] VehiclesFilenames = XDocument.Parse(@"<VehicleList>
                                      <Vehicle>
                                        <Filename>CriminalCar.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>PoliceCar.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>ChaseBear1.xml</Filename>
                                      </Vehicle>
                                        <Vehicle>
                                        <Filename>ChaseGiraffe1.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>LowEndCar.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>SportsCarRed.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>SportsCarGreen.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>SportsCarBlue.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>SportsCarBlack.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>SportsCarPink.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>SportsCarSilver.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>SportsCarWhite.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>SportsCarGold.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>SedanCarRed.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>SedanCarSilver.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>SedanCarBlue.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>SedanCarBlack.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>SedanCarPink.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>SedanCarBrown.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>SedanCarWhite.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>CompactCarRed.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>CompactCarYellow.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>CompactCarPurple.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>CompactCarBlack.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>CompactCarPink.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>CompactCarGreen.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>CompactCarWhite.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>LowEndCarRed.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>LowEndCarGreen.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>LowEndCarBlue.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>LowEndCarBlack.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>LowEndCarPurple.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>LowEndCarYellow.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>LowEndCarWhite.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>LowEndCarGold.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>FireTruck1.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>Ambulance1.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>ChaseCar1.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>Sedan1.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>BearCarPink.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>BearCarLightBlue.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>BearCarLimeGreen.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>BearCarYellow.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>GiraffeCarBlue.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>GiraffeCarMaroon.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>GiraffeCarSilver.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>CustomSportsCarFlames.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>CustomSportsCarTribal.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>CustomSportsCarRacing1.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>CustomSportsCarRacing2.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>BasicHelicopter.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>MedicalHelicopter.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>PoliceHelicopter.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>NewsHelicopter.xml</Filename>
                                      </Vehicle>
                                       <Vehicle>
                                        <Filename>BasicHelicopterGold.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>BasicHelicopterFullBlack.xml</Filename>
                                      </Vehicle>
                                       <Vehicle>
                                        <Filename>BasicHelicopterBlack.xml</Filename>
                                      </Vehicle>
                                       <Vehicle>
                                        <Filename>BasicHelicopterBlue.xml</Filename>
                                      </Vehicle>
                                       <Vehicle>
                                        <Filename>BasicHelicopterGreen.xml</Filename>
                                      </Vehicle>
                                       <Vehicle>
                                        <Filename>BasicHelicopterPink.xml</Filename>
                                      </Vehicle>
                                       <Vehicle>
                                        <Filename>BasicHelicopterRed.xml</Filename>
                                      </Vehicle>
                                       <Vehicle>
                                        <Filename>BasicHelicopterWhite.xml</Filename>
                                      </Vehicle>
                                       <Vehicle>
                                        <Filename>Helicopter_CustomFlames.xml</Filename>
                                      </Vehicle>
                                       <Vehicle>
                                        <Filename>Helicopter_CustomShark.xml</Filename>
                                      </Vehicle>
                                      <Vehicle>
                                        <Filename>ChaseBear2.xml</Filename>
                                      </Vehicle>
                                    </VehicleList>").Descendants("Vehicle")
                                    .Select(b => b.Element("Filename")?.Value)
                                    .Where(f => !string.IsNullOrEmpty(f))
                                    .ToArray();

        public static string[] ExpensionFilenames = new string[] { "Zoo", "TransUtopia", "StuntPack", "Racing", "NuclearPower", "Helicopters",
            "GloboSyn", "CrimeAndPunishment", "AmusementPark", "BuildingPack_Winter", "BuildingPack_OceanBreeze", "BuildingPack_Halloween", "BuildingPack_Gold" };
    }
}
